CREATE EVENT IF NOT EXISTS agendar_tab_mart_atividades
ON SCHEDULE
    EVERY 1 DAY
    STARTS TIMESTAMP(CURRENT_DATE) + INTERVAL 23 HOUR + INTERVAL 45 MINUTE
ON COMPLETION PRESERVE
DO
	CALL criar_tabela_atividade();