CREATE EVENT IF NOT EXISTS agendar_tab_mart_questoes
ON SCHEDULE
    EVERY 1 DAY
    STARTS TIMESTAMP(CURRENT_DATE) + INTERVAL 23 HOUR + INTERVAL 50 MINUTE
ON COMPLETION PRESERVE
DO
    CALL criar_tabela_agendada();